### ISSUE TITLE
Vim spacing configuration magically change from spaces/tabs when using the application

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/docker-odoo-image#223]
## Current Behavior

Current spacing rules in vim are using a tab with 4 spaces.
For some unknown reason, when I am using vim this rules just get missed and when I try to tab a actually tab is added instead the 4 blank spaces.

In order to fix, I use to configure again the tabs in a live vim with this command
```
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
```
and to fix the already introduced tabs 
```
:%s/\t/    /g
```

**NOTE: You can use also `:retab` for fix the tabs (thanks @luistorresm for this command)**

But, in some point the configuration is lost again and use tab character instead spaces.
This is a really annoying in python files since when I try to save the file or run the file a indentation error will occurs.

## Expected Behavior

I will like that vim spacing config remains to 4 spaces so I have not need to deal with indentation errors.

---

HINT: As far I know this error it seems to be related to a bug with vim-spf13, but I have not confirmed this

**Comment by zaoral** [comment]
ping @JesusZapata

**Comment by zaoral** [comment]
Hi @JesusZapata any news about this issue?

**Comment by JesusZapata** [comment]
@zaoral 
I don't know how to fix this issue, I can't not reproduced
When the big imagen is build the version of spf13 used is `3.0` , this version have the last updated
In some cases the same thing happened to me, but I think it's because of a combination of keys

**Comment by moylop260** [comment]
Sometimes I lost the color parser.
This occurs opening a file with vim from different shell sessions after a warning message of opened file. (I don't have the right steps because is a flaky too)

But @josemoralesp told me that the folder `~/.vimviews/` and `~/.vimswap/` is corrupted when this occurs. So deleting this folder we should have a vim reset.

But I don't know if there is a VIM issue about or if this is related with this one.

@josemoralesp @hbto Do you know something about?

**Comment by hbto** [comment]
I have been dealing with the same issue for a while
I haven't come to know what is the cause of the problem,
some time ago I just thought it was because of the :set paste command
but later I just disregarded the idea.

I have even thought that same idea of yours @moylop260 but It just
has happened in newly created containers where no other buffer/swapfile
has already been created.

 then I have had to apply the same fixing than
@zaoral,

BTW :retab is rather easier to use than :%s/\t/ /g

Regards.

Quien suscribe,

*Hbto*

**Comment by zaoral** [comment]
> @zaoral
> I don't know how to fix this issue, I can't not reproduced
> When the big imagen is build the version of spf13 used is 3.0 , this version have the last updated
> In some cases the same thing happened to me, but I think it's because of a combination of keys

@JesusZapata 
As I reported early in this issue, I am not aware about how this bug appears. IMHO the theory of a combination of keys I think is really not strong since I have heard that many of our co-workers present this same issue and I think that it's very weird that all have the same error when we use the keyword. I think it's a lot of coincidence.

@hbto  thanks for :retab command.

**Comment by josemoralesp** [comment]
I had this error once, when I changed between `:set paste` and `:set nopaste`. But this error hasn't happened to me again. To fix it, I used the options mentioned above by @zaoral. After that, I haven't seen this error in my instances.

**Comment by lescobarvx** [comment]
￼I fix this error by doing `:set expandtab`

I hope this method works for you

**Comment by moylop260** [comment]
I can reproduced it using:

```bash
vim my_file.py
# vim command: 
#     :set nopaste
# paste text
:wq
vim my_file.py
# vim command: 
#   i
# press <tab> or > or < keys.
```

**Comment by zaoral** [comment]
Hi guys
Any news about this issue?

**Comment by moylop260** [comment]
We can fix it since that is a real issue from vim.
Maybe we should create a issue from vim project with the steps to reproduce it
