### ISSUE TITLE
Use original odoo/requirements.txt to install packages

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#250]
@ruiztulio We have created a PR in order to use the original odoo/requirements.txt:
 - https://github.com/OCA/maintainer-quality-tools/pull/455

We could use a similar behaviour to build the images.

(Could you re-assign it, please?)

**Comment by ruiztulio** [comment]
@moylop260 we actually use it when we clone the [odoo and modules](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/build-image.sh#L16-L19) and with [this](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/gen_pip_deps) we generate a full requirements file which are installed [here](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/library.sh#L69).

For the deployment process we do a similar process where we install the [full_requirements](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/templates/files/install_deps.py#L39) generated by [rengenv](https://git.vauxoo.com/vauxoo/deployv/blob/master/deployv/instance/instancev.py#L527) in this way no matter what version we have installed in the base image it will always will install the versions in the requirements files. So, the only purpouse of the full requirements we [generated by hand](https://github.com/Vauxoo/docker-odoo-image/blob/master/odoo100/scripts/10.0-full_requirements.txt) is to speed up a little bit the build process (I'm using 10.0 as an example, but the same apply to 9.0 and 8.0 images) because there are a few dependencies from private repos too.

If you want we can remove the full requirements file or only remove the odoo dependencies from there but having the two places where we can download the original requirements from Odoo, do you think it is necessary to do so?

**Comment by moylop260** [comment]
I understand that we have a generated by hand requirements.txt file to cache the packages.
We need to update this file to work fine with the cache because we have the following differences:

10.0-odoo:
 - PyYAML==3.12
 - ofxparse==0.16

10.0-by-hand:
 - PyYAML
 - ofxparse and ofxparse==0.15 (2 times)
 - num2words 2 times too

For 9.0 and 8.0 there are similar examples then the cache won't work because the `pip install -U` spent time in uninstall the old package to install the new one.

But is not a critical issue.

So we should let open this issue a time to see if the issue increase level or not.

**Comment by ruiztulio** [comment]
@moylop260 ok, so we will remove the odoo dependencies from the full requirements so it installs directly the ones from the Odoo requirements.txt
