### ISSUE TITLE
odoo-shippable image: postgres user doesn't have PostgreSQL configuration file access

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/docker-odoo-image#327]
Saw 
```
docker run -it --rm vauxoo/odoo-80-image-shippable-auto ls -lah /etc/postgresql-common/common-vauxoo.conf
-rw-r--r-- 1 root root 472 Jul  8 01:01 /etc/postgresql-common/common-vauxoo.conf
```

Expected
postgres group access to this file

**Comment by luisg123v** [comment]
@moylop260  
Are you sure this is not an expected behavior?

Config files are usually owned by root.

**Comment by moylop260** [comment]
The postgresql service is executed with the postgres user.
If postgres doesn't have permission then never will use it.

**Comment by moylop260** [comment]
what do you think @ruiztulio

**Comment by ruiztulio** [comment]
@moylop260 The postgres user have permissions to read the file, as ponted by @luisg123v that is the standard permission pattern for postgres, the file is owned by root and is read only for the group and other users: -(rw-)(r--)(r--).

The postgres user can't change it and this is expected behavior, but is able to read it

**Comment by moylop260** [comment]
For record, use root user if you like change this file and reload postgresql configuration:
 - `docker exec --user=root -it CONTAINER_ID bash`
